project:
  type: book
  output-dir: _book
  execute-dir: project
  resources:
    - data/hospital.csv

lang: id

book:
  title: "Analisis Efisiensi Fasilitas Kesehatan"
  subtitle: "Aplikasi Menggunakan Software R"
  author:
    - Firdaus Hafidz
    - Muhammad Fikru Rizal
  date: last-modified
  date-format: "D MMMM YYYY"
  repo-url: https://github.com/fikrurizal/buku-efisiensi
  repo-actions: [edit, issue]
  search: true
  chapters:
    - index.qmd
    - kata-pengantar.qmd
    - singkatan.qmd
    - chapters/01-dasar-efisiensi.qmd
    - chapters/02-pengukuran-efisiensi.qmd
    - chapters/03-pengantar-r.qmd
    - chapters/04-analisis-rasio.qmd
    - chapters/05-dea.qmd
    - chapters/06-sfa.qmd
    - chapters/07-isu-pengukuran.qmd
    - daftar-pustaka.qmd
    - tentang-penulis.qmd

crossref:
  fig-prefix: Gambar
  tbl-prefix: Tabel
  eq-prefix: Persamaan

execute:
  freeze: auto
  warning: false

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc-depth: 3
    number-depth: 2
    code-link: true
    code-copy: true
    fig-cap-location: bottom
    tbl-cap-location: top
