# Pengukuran Efisiensi pada Fasilitas Kesehatan di Negara Berpendapatan Rendah dan Menengah: Tinjauan Pustaka {#sec-tinjauan}

## Pengantar

Setelah membangun pemahaman tentang aspek-aspek metodologi pengukuran efisiensi pada bab sebelumnya, kami sekarang beralih ke tinjauan pustaka tentang efisiensi fasilitas kesehatan dalam konteks negara berpendapatan rendah dan menengah (NBRM). Tinjauan seperti itu diperlukan bagi para pembuat kebijakan di NBRM yang harus menggunakan bukti terbaik untuk memandu keputusan-keputusan terkait efisiensi. Bab ini dengan demikian bertujuan untuk meninjau kembali metode-metode pengukuran efisiensi dengan demikian dapat menginformasikan studi efisiensi di masa depan di semua tingkat fasilitas kesehatan baik di pengaturan umum maupun swasta.

Tinjauan pustaka ini mensintesis pengaturan studi pengukuran efisiensi dalam NBRM; teknik, variabel input dan output, serta variabel kontekstual yang digunakan dalam studi; masalah metodologi; dan hasilnya. Bagian pendahuluan bab ini memberikan latar belakang pada sektor kesehatan dan efisiensinya dalam NBRM dan negara-negara berpenghasilan tinggi (NBT). Bagian 4.2 memberikan metode-metode yang digunakan untuk mensintesis bukti, sedangkan bagian 4.3 berisikan hasil-hasil dari tinjauan pustaka. Hasil-hasil tersebut dibahas lebih lanjut pada bagian 4.4, termasuk poin-poin perbedaan dalam konteks NBT. Bagian 4.4 juga menguraikan implikasi kebijakan dari hasil yang diperoleh serta keterbatasannya dan beberapa rekomendasi untuk pekerjaan lebih lanjut. Bagian terakhir menyajikan kesimpulan dari keseluruhan bab.

## Metode

### Strategi Pencarian

Tinjauan dari lima pangkalan data literature dilakukan bersama dengan pancarian manual dari artikel-artikel yang dipublikasikan dalam daftar referensi dan terbitan publikasi sampai minggu keenam tahun 2018. Tidak ada batasan waktu yang diberlakukan karena penulis ingin menangkap seluruh cakupan studi efisiensi.

Basis data yang digunakan dalam kajian ini adalah sebagai berikutt: MEDLINE (Ovid), Embase Classic + Embase (Ovid), Global Health (Ovid), and untuk literature abu-abu. Pencarian dirancang unutk mengidentifikasi studi efisiensi fasilitas kesehatan pada NBRM dengan mengkombinasikan konsep pencarian 'efisiensi', 'fasilitas kesehatan', dan 'negara berpendpatan rendah dan menengah'. Strategi pencarian yang disarankan oleh Dudley & Garner (2011) untuk 'negara berpenghasilan rendah dan menengah' diadopsi dalam tinjauan ini.

### Kriteria Inklusi

Studi yang dianggap memenuhi syarat untuk inklusi diukur efisiensi, produktivitas atau kinerja sebagai cara membandingkan layanan antara berbagai fasilitas kesehatan. Unit studi ini adalah fasilitas kesehatan seperti rumah sakit, fasilitas kesehatan primer, atau panti jompo baik di sektor publik atau swasta. Semua jenis studi analisis kuantitatif dengan informasi empiris yang berkaitan dengan pengukuran efisiensi layanan di tingkat fasilitas kesehatan dipertimbangkan. Karena fokus kami pada NBRM, kami mengeksklusi studi yang dilakukan di negara-negara yang ditetapkan oleh Bank Dunia sebagai NBT (negara-negara dengan pendapatan per kapita USD 12.616 atau lebih (Bank Dunia, 2015a). Sebagai tambahan, studi dalam bahasa selain bahasa Inggris dieksklusi.

### Pengumpulan data dan analisis

Semua judul dan abstrak yang diperoleh dari pencarian elektronik kemudian dikumpulkan menggunakan database manajemen referensi (EndNote) dan dibersihkan dari duplikat. Judul dan abstrak disaring berdasarkan kriteria inklusi dan eksklusi dan salinan teks lengkap dari studi yang terinklusi kemudian diunduh dan dinilai. Setelah studi yang dimasukkan diidentifikasi, data diekstraksi menggunakan formulir yang dikembangkan untuk tujuan studi ini. Studi yang sulit dipresentasikan kepada pengawas PhD dari kandidat (Tim Ensor dan Sandy Tubeuf) untuk diskusi lebih lanjut. Beberapa artikel diidentifikasi secara independen dari proses pencarian. Untuk setiap studi, hal-hal berikut diekstraksi: tujuan, negara, wilayah geografis menurut pengelompokan Bank Dunia, jenis fasilitas kesehatan, ukuran sampel, tahun, metode, orientasi, variabel input, variabel keluaran, variabel keluaran variabel kontekstual, hasil, dan keterbatasan. Karena penelitian yang dimasukkan terlalu heterogen untuk melakukan meta-analisis, sintesis naratif dilakukan (Popay et al., 2006). Informasi dari penelitian dikelompokkan sesuai dengan karakteristik penelitian dan kemudian diperiksa dalam ringkasan yang ditabulasi.

### Validitas Studi

Validitas metodologi dinilai menggunakan alat validitas yang diadaptasi dari instrumen yan digunakan pada tinjauan sistematis yang dipublikasikan rumah sakit (Hadji et al., 2014). Alat validitas mencakup tiga belas item yang berhubungan dengan sampelm indicator, dan metode statistik (Tabel B.1 di Lampiran B). Setiap item diberikan satu poin jika jawabannya adalah "Ya" dan nol poin jika jawabannya adalah "Tidak", menghasilkan skor mulai dari 0 sampai 13 untuk setiap studi. Studi yang memiliki skor kurang dari 6 poin dianggap memiliki validitas yang rendah, sedangkan skor 6 sampai 8 memiliki validitas sedang, dan skor lebih dari sama dengan 9 memiliki validitas yang tinggi.

### Teknik pengukuran

Analisis rasio (AAR efisiensi teknis) atau biaya input ke rasio output (AR efisiensi ekonomi) (Bitran, 1992). RA biasanya terbatas pada satu input (contohnya tempat tidur). Namun, dapat juga dilakukan analisis rasio yang simultan di berbagai input (Lasso, 1986). Tidak seperti AR, teknik parameter memperkirakan hubungan antara satu varibet tergantung dengan beberapa variable bebas dari input maupun output berdasarkan bentuk fungsional tertentu (Jacobs et al., 2006). Pada tinjauan ini, kami membagi metode parametrik menjadi estimasi ekonometrik (EE) dan analisis perbatasan stokastik. EE memperkirakan efisiensi teknis atau efisiensi ekonomi menggunakan regresi kuadrat terkecil antara input dan output. Model fungsi produksi menentukan faktor yang secara signifikan berhubungan dengan tingkat output, dan model fungsi biaya yang mengidentifikasi faktor-faltor penentu biaya (Berman et al., 1989; Somanathan et al., 2000). Model respon rata-rata ini mengevaluasi komponen infesiensi dengan kesalahan acak (Schmidt, 2008).

## Hasil

### Deskripsi umum dari studi terinklusi

Pencarian literatur mengidentifikasi total 6.946 studi yang berpotensi relevan dari lima database, dan pencarian manual mengidentifikasi 12 artikel. Setelah duplikat dihapus, 5.376 judul dan abstrak disaring, sebanyak 5.167 studi dikeluarkan. Alasan paling umum untuk dieksklusi adalah bahwasanya tujuan dari penelitian ini bukan untuk menilai efisiensi fasilitas kesehatan dan settingnya bukan NBRM. Dua ratus sembilan studi yang berpotensi relevan diambil untuk penilaian teks lengkap; 72 studi dieksklusi dari tinjauan teks lengkap karena teks lengkap tidak tersedia atau tidak dalam bahasa Inggris, dan 137 studi dimasukkan dalam analisis (Gambar 4.1).

Mengenai validitas studi, dari 137 studi terinklusi, 107 studi (78%) memiliki skor validitas tinggi dan 30 (22%) memiliki skor validitas sedang. Sebagian besar penelitian dengan validitas sedang memiliki satu atau lebih masalah berikut: 1) penilaian hanya satu jenis fasilitas kesehatan, 2) perhitungan ukuran sampel tidak disuguhkan dengan jelas, dan 3) periode studi tidak didefinisikan secara jelas. Sebaliknya, sebagian besar studi dengan skor tinggi tidak memiliki masalah di atas dan juga lebih cenderung menggunakan indikator yang berbeda untuk mengukur dampak pada efisiensi dan untuk membenarkan metode statistik.

### Setting

Empat puluh tiga penelitian (31%) dilakukan di Afrika sub-Sahara (Gambar 4.2), dengan konsentrasi di Ghana, Kenya, dan Afrika Selatan. Studi-studi ini terdiri dari analisis antar negara dari 48 negara di tujuh wilayah. Ada lima studi efisiensi antar negara, empat di antaranya dilakukan di Afrika (Mills et al., 1997; Soucat et al., 1997; Levin et al., 2003; Obure et al., 2016); yang kelima termasuk beberapa negara Afrika serta Honduras dan Moldova (Brenzel et al., 2015). Tujuan utama dari penelitian tersebut adalah untuk meningkatkan kualitas informasi dan menguji efisiensi dalam seting yang berbeda. Keterwakilan analisis antar negara beragam; misalnya, penelitian di Iran menggunakan data dari hanya satu rumah sakit menggunakan data panel lima tahun (Masoompour et al., 2015). Namun, studi nasional tentang fasilitas kesehatan di Meksiko mencakup total sampel hingga 2.105 fasilitas (Keith & Prior, 2014). Tidak ada perbedaan nyata dalam jenis metode yang digunakan di masing-masing daerah (Gambar 4.2). AED tetap menjadi teknik yang paling sering digunakan untuk pengukuran efisiensi di semua wilayah. AR digunakan di sebagian besar wilayah, tetapi tidak di Eropa dan Asia Tengah. Selain itu, hanya sejumlah kecil studi yang menerapkan SFA dan EE. SFA hanya digunakan dalam studi di sub-Sahara Afrika, Timur Tengah dan Afrika Utara, dan kawasan Asia Timur dan Pasifik, sedangkan EE sendiri digunakan dalam studi di Asia Selatan, Eropa dan Asia Tengah.

Fasilitas kesehatan dikategorikan sebagai berikut: rumah sakit, fasilitas kesehatan primer, dan jenis fasilitas kesehatan lainnya seperti pusat nutrisi masyarakat, klinik kedokteran gigi, dan fasilitas dialisis. Delapan puluh delapan studi (64,2%) dilakukan di rumah sakit, 29 studi (21,2%) terjadi di pengaturan perawatan primer, 11 studi (8,0%) menganalisis rumah sakit dan fasilitas perawatan primer, dan sembilan studi (6,6%) dilakukan di jenis fasilitas kesehatan lainnya (Tabel 4.1). Sehubungan dengan kepemilikan, mayoritas fasilitas kesehatan yang diteliti berada di sektor publik (n = 97, 70,8%), 29 studi (21,2%) menganalisis fasilitas kesehatan publik dan swasta, dan hanya delapan studi (5,8%) yang menganalisis kesehatan swasta fasilitas yang eksklusif. Informasi kepemilikan sisanya 2,2% dari fasilitas yang diteliti tidak tersedia.

### Teknik

Jumlah studi yang menggunakan beberapa teknik untuk mengukur efisiensi telah meningkat secara dramatis selama beberapa tahun terakhir (Gambar 4.3). Sebagian besar studi (91%) yang termasuk dalam tinjauan ini dipublikasikan setelah tahun 2000, dan sebagian besar menggunakan metode analisis yang relatif modern. Hampir sepertiga dari penelitian menerapkan satu dari dua jenis analisis AR. Jenis pertama adalah rasio input-ke-output fisik (efisiensi teknis), misalnya, tingkat pergantian tempat tidur dan tingkat hunian tempat tidur. Sepuluh studi menggunakan model Pabon-Lasso, yang menerapkan beberapa indikator AR secara bersamaan. Jenis yang kedua adalah rasio input biaya terhadap output (efisiensi ekonomi), misalnya, biaya rata-rata per admisi dan biaya rata-rata per kunjungan rawat jalan. Sisa penelitian (n = 95, 65,5%) menggunakan SFA, DEA atau ccampuran berbagai metode. Kurang dari tiga persen dari studi menerapkan EE secara eksklusif. Penggunaan AED dalam studi yang termasuk dalam tinjauan literatur ini terlihat mulai tahun 2000 (Gambar 4.3); AED memiliki kelebihan karena mampu menangani banyak input dan output dan tidak memerlukan bentuk fungsional yang ditentukan.

Dari 137 studi, 82 studi menggunakan DEA sendiri atau bersama-sama dengan analisis tahap kedua, termasuk sembilan belas studi yang juga termasuk indeks Malmquist. Perlu dicatat bahwa studi yang menggunakan DEA berorientasi terutama pada input daripada output, sementara hanya sejumlah kecil studi yang menerapkan orientasi input dan output. Dengan memeriksa berbagai tingkat perawatan mengungkapkan bahwa penelitian di rumah sakit sebagian besar berorientasi input sedangkan yang di fasilitas pelayanann primer didistribusikan secara merata antara input dan berorientasi output (Gambar 4.4). Ini mungkin karena manajer rumah sakit memiliki kontrol lebih besar atas input, yang memungkinkan mereka untuk meminimalkan penggunaan sumber daya dengan tetap mempertahankan tingkat output yang sama. Di sisi lain, manajer layanan primer biasanya memiliki kontrol terbatas atas tingkat input; tujuan mereka adalah untuk memaksimalkan hasil yang dihasilkan. Mengenai pengembalian skala, sebagian besar studi, terutama yang dilakukan di rumah sakit, menggunakan VRS.

### Variabel input

Dari 137 studi pengukuran efisiensi dalam literatur yang dipublikasikan, 82 studi menggunakan hitungan sumber daya fisik sebagai input, 23 studi menggunakan input keuangan, dan 32 studi menggunakan sumber daya fisik dan input keuangan (Tabel 4.1). Variabel input fisik termasuk berbagai jenis barang modal (misalnya jumlah tempat tidur, ukuran fasilitas, dan jumlah peralatan medis yang tersedia), serta berbagai jenis tenaga kerja atau bahan (misalnya jumlah dokter dan perawat dan jumlah obat-obatan dan persediaan medis). Input keuangan mencakup total pengeluaran, input modal (mis. biaya untuk merekonstruksi fasilitas kesehatan, depresiasi peralatan), dan berbagai jenis pengeluaran tenaga kerja / material (mis. gaji, pengeluaran obat-obatan, dan pengeluaran non-tenaga kerja). Jenis input lain juga ditemukan, termasuk campuran layanan sebagai proksi untuk kompleksitas layanan dan kualitas manajemen yang diukur dengan upaya untuk memenuhi harapan pelanggan (Tabel 4.2).

### Variable output

Sebagian besar pengukuran (89.1%) dari literature yang terpublikasi menggunakan layanan kesehatan sebagai output. Item layanan kesehatan yang paling sering di rumah sakit adalah 1) jumlah kunjungan rawat jalan, admisi atau boleh pulang dan 2) hari rawat inap (Tabel 4.3).

Namun demikian, karena sebagian besar studi menggunakan kumpulan output, sehingga tidak memungkinkan untuk memisahkan layanan berdasarkan departemen. Output yang biasa digunakan dalam seting layanan primer adalah kunjungan rawat jalan dan layanan lainnya termasuk jumlah anak yang diimunisasi lengkap, jumlah individu yang terdaftar dalam layanan gizi, dan jumlah resep. Dalam beberapa penelitian, keluaran dikategorikan berdasarkan jenis layanan (mis. Keluarga berencana, layanan kesehatan anak) dan berdasarkan kondisi (mis. tifoid, malnutrisi)

Empat studi menyesuaikan jumlah kasus menggunakan indeks campuran kasus untuk memperlakukan semua layanan secara merata (Arocena & Garc ́ıa-Prado, 2007; Jian et al., 2009; de Castro Lobo et al., 2010; Rajasulochana & Dash, 2012). Dua penelitian (Arocena & Garc ́ıa-Prado, 2007; de Castro Lobo et al., 2010) menggunakan pembobotan kelompok terkait diagnostik (DRG), dan satu penelitian (Rajasulochana & Dash, 2012) menggunakan intensitas kasus meternal dan neonatal yang rumit. Tidak ada penelitian yang menggunakan hasil kesehatan dari populasi, seperti tingkat kematian ibu atau tingkat kematian anak sebagai hasil. Dua penelitian (Sahin & Ozcan, 2000; Yang & Zeng, 2014) menggabungkan hasil pasien seperti tingkat kematian untuk pasien yang dirawat, yang digunakan sebagai hasil yang tidak harapkan. Kualitas layanan terkadang digunakan untuk menyesuaikan output; diproksi dengan jumlah penerimaan ulang (Arocena & Garc ́ıa-Prado, 2007), rasio kelangsungan hidup dan kinerja (Ketabi, 2011), dan kepuasan pasien (Razzaq et al., 2013). Ukuran output lainnya adalah kinerja keuangan, yang diaplikasikan oleh enam studi. Kinerja keuangan diukur menggunakan pendapatan fasilitas kesehatan (Zaim et al., 2008; Gai et al., 2010; Aboagye & Degboe, 2011; Alaghemandan et al., 2014), nilai pembelian (Rattanachotphanit et al., 2008), dan pengembalian aset dan margin operasi (Guerra et al., 2012).

### Variabel kontekstual

Lebih dari setengah (61.3%) dari studi yang diinklusi menggunakan analisis lebih jauh untuk memeriksa penentu efisiensi fasilitas kesehatan. Rata-rata, tiga variable kontekstual dianalisis pada setiap studi, dengan rentang jumlah variable kontekstual dari satu hingga dua belas per studi. Variabel kontekstual internal yang biasa digunakan adalah kepemilikan (contoh: public maupun swasta), tipe fasilitas kesehatan ( contoh: fasilitas dokter umum atau spesialis), indikator performa ( contoh: tingkat penggunaan tempat tidur, rerata lama rawat inap), indikator kualitas (contoh: kepuasan pasien, tingkat mortalitas) dan layanan kesehatan spesifik (Tabel 4.4). Variabel kontekstual eksternal yang digunakan adalah lokasi geografis (misalnya wilayah, perkotaan atau pedesaan), demografi (misalnya cakupan ukuran populasi, tingkat pendidikan penduduk), situasi ekonomi (misalnya pendapatan per kapita provinsi, nilai aset rumah tangga), tren waktu, dan konsentrasi pasar (Tabel 4.4).

### Masalah metodologi

Analisis dari keterbatasan diambil dari keterbatasan yang diidentifikasi oleh penulis dari masing-masing penelitian (Gambar 4.5). Tiga puluh lima studi (26%) menunjukkan kurangnya ketersediaan indikator kualitas, yang menyebabkan ketidakmampuan untuk menyesuaikan variabel output untuk kualitas. Tiga puluh empat penelitian (25%) menyatakan ukuran sampel kecil sebagai batasan. Rata-rata, ukuran sampel fasilitas kesehatan yang diperiksa dalam studi adalah 101, dengan rata-rata 74 fasilitas untuk analisis yang dilakukan di rumah sakit dan 102 fasilitas dalam setting layanan primer. Jumlah rata-rata output adalah 3 (kisaran: 1 hingga 14); jumlah rata-rata input juga 3 (kisaran: 1 hingga 11). Dua puluh tiga studi (17%) menunjukkan bahwa data biaya dan harga sulit dikumpulkan. Tantangan ini mengarahkan para peneliti untuk menggunakan AED, bukan SFA, yang membutuhkan data keuangan. Kurangnya informasi campuran kasus untuk melakukan pembobotan keluaran juga dicatat sebagai keterbatasan dalam dua puluh empat studi (18%). Tantangan ini mengarahkan para peneliti untuk menggunakan DEA, bukan SFA, yang membutuhkan data keuangan. Kurangnya informasi campuran kasus untuk melakukan pembobotan keluaran juga dicatat sebagai keterbatasan dalam dua puluh empat studi (18%).

### Output

Studi-studi yang terinklusi di tinjauan ini melaporkan efisiensi rlatif sebagai keluaran studi. Studi yang menggunakan teknik AR mejelaskan efisiensi dengan menentukan variasi indikaator rasio di antara fasilitas kesehatan. Sebagai tambahan, penelitian yang menggunakan AR dengan model Pabon-Lasso menjelaskan efisiensi dengan menilai posisi masing-masing fasilitas kesehatan dalam diagram menurut tingkat hunian tempat tidur rata-rata dan tingkat turnover tempat tidur. Ukuran AED dan SFA yang biasanya digunakan yang disajikan dalam studi adalah skor efisiensi teknis, pengembalian skala, peringkat fasilitas kesehatan, dan perkiraan pengurangan input atau peningkatan output yang diperlukan untuk menjadi efisien. Variasi yang luas dalam hasil pengukuran efisiensi juga ditemukan.

## Pembahasan

### Teknik

Sebagian besar studi terinklusi mengandalkan metode seperti AR dan AED. AR awalnya digunakan karena manfaatnya: sederhana, mudah dihitung, berbiaya rendah dan dapat dilakukan dengan sampel yang sedikit (Bitran, 1992). Terlebih, walaupun AR tidak dapat menangani beberapa produk, AR menyajikan informasi yang berguna untuk mendeteksi inefisiensi. Dengan demikian, dalam keadaan tertentu yang melibatkan keterbatasan waktu, data, keahlian, atau anggaran, pembuat kebijakan dan peneliti lebih memilih AR sebagai alat untuk membandingkan efisiensi di seluruh organisasi layanan kesehatan. Temuan ini tidak unik untuk NBRM; tinjauan pengukuran efisiensi di Amerika Serikat menemukan bahwa 44% dari studi menggunakan AR sebagai metode statistik (Hussey et al., 2009). Namun, AR memiliki keterbatasan termasuk asumsi mengenai alokasi biaya dan kesulitannya dalam mendeteksi variasi kualitas dan campuran kasus di antara penyedia (Bitran, 1992).

Secara umum penerapan AR di NBT lebih maju dibanding di NBRM karena menggunakan output yang disesuaikan seperti rata-rata lamanya inap disesuaikan dengan keprahannya keparahan(Hussey et al., 2009). AED menjadi pilihan populer bagi para peneliti di NBRM dan NBT untuk mengatasi keterbatasan AR sejak tahun 2000 (Hollingsworth, 2008; Hussey et al., 2009). Keuntungan utama AED adalah dapat digunakan dengan banyak input dan output. Namun, baik AR dan AED menjadi bermasalah ketika ada penyimpangan dalam sampel. EE memberikan keuntungan dari tinjauan yang lebih baik tentang perubahan dalam output atau total biaya sebagai respon terhadap perubahan input dan campiran layanan melalui fungsi produksi atau pembiayaan. EE telah diterapkan di NBT sejak 1970-an, tetapi baru mulai digunakan dalam NBRM pada akhir 1980-an, ketika penggunaannya masih terbatas (Bitran, 1992). Kekurangan data, seperti ketersediaan serta inkonsistensi antara penyedia, adalah kendala utama saat menggunakan EE. Terlebih, EE tidak dapat memisahkan antara inefisiensi sesungguhnya dan kesalahan acak (Barnum & Kutzin, 1993; Schmidt, 2008). Sebagian besar studi yang menerapkan EE dalam NBT menggunakan fungsi biaya, sedangkan penerapan fungsi biaya atau produksi dalam NBRM jarang terjadi karena keterbatasan ketersediaan data biaya dan harga (Conteh & Walker, 2004).

Studi efisiensi baik pada NBT dan NBRM semakin menggunakan SFA; namun, AED tetap merupakan teknik yang dominan (Hollingsworth, 2003, 2008). SFA mengandalkan sumber yang besar dan terperinci, terutama harga input dan informasi keuangan lainnya, untuk data. Fungsi pembiayaan lebih umum diterapkan dalam SFA daripada fungsi produksi karena biaya dapat dengan mudah digabungkan menjadi ukuran tunggal yang diperlukan untuk batas SFA (Cylus et al., 2016). Namun, persyaratan ini membatasi penerapan SFA ketika ketersediaan data terbatas, yang merupakan masalah di NBRM khususnya.

Penting untuk digarisbawahi bahwa hanya lima studi yang tampaknya telah menerapkan SFA saja, sementara empat lainnya menggunakannya bersamaan dengan metode lain untuk membandingkan hasil. Selain itu, kompleksitas SFA dapat mencegah peneliti untuk menggunakannya, karena hasil yang dicapai dengan menggunakan metode ini sulit untuk ditafsirkan oleh pembuat kebijakan. Tiap teknik memiliki kelebihan dan kekurangan masing-masing; tidak ada consensus yang jelas mengenai teknik yang mana yang paling baik. AR dari efisiensi taknis dan AED tampaknya menjadi teknik yang lebih dipilih untuk mengukur efisiensi di NBRM ketika pembuat kebijakan membutuhkan bukti yang cepat, jelas, sederhana dan praktis, di mana informasi pembiayaan tidak tersedia dari sistem informasi yang rutin.

### Orientasi

Terlepas dari teknik yang digunakan untuk mendapatkannya, hasil efisiensi dapat diintepretasikan dengan berbagai cara tergantung pada orientasinya (Hussey et al., 2009). Tinjauan ini menemukan jumlah yang seimbang dari studi yang menerapkan orientasi input dan output. Merealokasikan kelebihan staf medis dan mengurangi kapasitas fasilitas kesehatan adalah contoh peningkatan efisiensi berdasarkan input. Namun, dari sudut pandang etika, ini mungkin bukan cara yang tepat untuk mengurangi limbah di fasilitas yang menghadapi kesulitan dengan ketersediaan sumber daya (Kirigia et al., 2008a; Marschall & Flessa, 2011).

Orientasi output (contohnya meningkatkan kegiatan penjangkauan, mengurangi hambatan fisik dan keuangan, meningkatkan tingkat pemanfaatan, dan lain-lain.) mungkin dapat menjadi sikap yang lebih dapat diterima dalam konteks NBRM. Selain itu, orientasi input bisa sangat sulit diterapkan di fasilitas kesehatan yang dimiliki oleh pemerintah. Proses birokrasi dapat membuat prosedur perekrutan atau pemberhentian karyawan dan pembelian atau pembuangan aset menjadi rumit dan memakan waktu. Namun, jenis orientasi ini mungkin dapat dilakukan jika fasilitas tersebut diberikan peningkatan otonomi sehubungan dengan keputusan manajemen sumber daya.

### Indikator

Hasil penelitian menunjukkan bahwa input fisik seperti infrastruktur dan campuran staf adalah variabel input yang paling sering digunakan untuk pengukuran efisiensi dalam NBRM ketika variabel yang terkait dengan layanan yang diberikan berbasis output. Hanya sebagian kecil dari penelitian yang menggunakan variabel yang berhubungan dengan ukuran finansial atau kualitas sebagai output. Temuan serupa dalam variabel input dan output ditemukan dalam NBT (Hussey et al., 2009). Meskipun obat-obatan merupakan indikator input yang dimaksudkan untuk memberikan manfaat dalam mendeteksi penggunaan obat generik yang kurang digunakan dan mahal, penggunaan obat yang tidak rasional, dan obat-obatan di bawah standar atau palsu, jenis variabel input ini kurang dalam sebagian besar penelitian (Chisholm & Evans, 2010).

Sehubungan dengan output, indikator yang terutama digunakan tidak dapat mendeteksi apakahuji dan prosedur telah diterapkan sesuai dengan kebutuhan pasien. Sebagian besar studi dalam tinjauan pustaka gagal menjelaskan tingkat keparahan kasus yang dirawat di berbagai fasilitas kesehatan dalam mengukur efektivitas layanan perawatan kesehatan. Kelalaian ini dapat menyebabkan salah tafsir dari pengukuran efisiensi karena output yang tidak dapat dibandingkan. Oleh karena itu perlu untuk memasukkan indikator kualitas (misalnya tingkat kematian, tingkat re-admisi dan indikator campuran kasus (misalnya tingkat kasus komplikasi, variasi kelompok diagnosis) untuk menyesuaikan output (Hollingsworth, 2008; Mutter et al., 2013; Varabyova & Schreyogg, 2013; Chowdhury et al., 2014; Ding, 2014; Yang & Zeng, 2014; Ineveld et al., 2015; Matranga & Sapienzab, 2015). Indikator kualitas digunakan dalam sejumlah cara untuk menyesuaikan output. Sebagian besar studi dalam tinjauan ini menerapkan kebalikan dari output yang tidak diinginkan, misalnya tingkat kematian, sebagai indeks indikator kualitas (Sahin & Ozcan, 2000; Ramanathan et al., 2003); teknik ini juga umum digunakan dalam NBT. Daripada tingkat kematian, dua dari studi NBRM menggunakan skor indeks komposit untuk kualitas layanan, serta indikator kualitas struktural dan proses (Aduda et al., 2015; Obure et al., 2016). Indikator kualitas yang diterapkan dalam setting NBT yang berasal dari informasi pasien, seperti rata-rata lamanya rawat inap dan kejadian yang tidak diharapkan (Ding, 2014; Yang & Zeng, 2014; Matranga & Sapienzab, 2015) dapat mwmbuktikan permaslahan dalam setting NBRM karena catatan medis yang tidak akurat (Wong & Bradley, 2009).

### Variabel kontekstual

Banyak penelitian menggabungkan variabel kontekstual, dan mereka sering menggunakan analisis dua tahap untuk mengidentifikasi faktor-faktor penentu efisiensi. Tahap pertama memperkirakan efisiensi teknis yang relatif dari fasilitas kesehatan menggunakan AED sedangkan tahap kedua adalah model regresi penjelas, biasanya Tobit atau regresi terpotong yang memprediksi skor efisiensi teknis menurut satu set variabel kontekstual (Hoff, 2007; McDonald, 2009; Simar & Wilson, 2011). Namun, ketika studi menerapkan SFA untuk mengukur efisiensi, pendekatan dua tahap tidak direkomendasikan karena bias yang timbul dari proses dan sifat statistik lainnya yang tidak diinginkan (Parmeter & Kumbhakar, 2014). Oleh sebab itu, faktor penentu efisiensi diidentifikasi menggunakan pendekatan satu tahap.

Dari sembilan studi yang menerapkan SFA, enam studi menganalisis variabel kontekstual. Empat studi (Lekprichakul, 2001; Atilgan, 2016; Chaabouni & Abednnadher, 2016; Wei et al., 2018) menerapkan pendekatan satu tahap sementara dua lainnya (Walker, 2006; Novignon & Nonvignon, 2017) menganalisis determinan dengan membandingkan secara deskriptif dan statistik menggunakan prosedur dekomposisi yang cocok dengan ANOVA, Pearson, dan Nopo. Variabel kontekstual mencakup faktor internal dan eksternal. Faktor internal adalah elemen dalam fasilitas kesehatan yang dapat dikendalikan manajer; faktor eksternal adalah elemen di luar fasilitas kesehatan yang tidak mungkin dikendalikan oleh manajer kesehatan. Dalam tinjauan kami, faktor kontekstual biasanya termasuk status kepemilikan, ukuran fasilitas kesehatan, dan status pengajaran sebagai faktor internal sementara geografi, demografi, dan status ekonomi populasi digunakan sebagai faktor eksternal. Studi dalam NBT umumnya menggunakan set variabel kontekstual yang sama (Lee et al., 2008a; Shreay et al., 2014), dengan kepemilikan yang paling sering digunakan bersama dengan ukuran dan kapasitas, tingkat spesialisasi, struktur pasar dan masalah pendanaan. Studi terbaru dalam NBT terkadang memasukkan indikator kualitas dalam analisis (Hollingsworth, 2003; Worthington, 2004; Herrera et al., 2014).

Kepemilikan publik dalam NBRM umumnya ditemukan berkorelasi dengan efisiensi yang lebih tinggi daripada kepemilikan pribadi, meskipun temuannya beragam. Jehu-Appiah et al. (2014) menemukan bahwa rumah sakit umum berkinerja lebih baik daripada swasta karena rumah sakit umum di NBRM bekerja di bawah batasan anggaran yang signifikan, memaksa mereka untuk memberikan perawatan medis dengan biaya lebih rendah. Namun, sebuah studi oleh Hatam et al. (2010) di Iran berpendapat bahwa sektor swasta lebih efisien daripada sektor publik karena tidak ada insentif bagi sektor publik untuk meminimalkan pengeluaran. Dalam NBT, ulasan oleh Herrera et al. (2014) menemukan bahwa kepemilikan tampaknya tidak mempengaruhi efisiensi. Perbedaan yang signifikan dalam hasil dan biaya kesehatan hanya ditemukan antara penyedia layanan swasta untuk profit dan penyedia nirlaba swasta; yang terakhir ditemukan lebih efisien. Tidak ada perbedaan signifikan yang ditemukan dalam efisiensi antara penyedia layanan publik dan dua kategori penyedia layanan swasta. Selain kepemilikan, tinjauan kami menemukan bahwa ukuran fasilitas yang diukur dengan jumlah tempat tidur dikaitkan dengan efisiensi. Temuan menunjukkan hasil yang beragam; beberapa penelitian menemukan bahwa ukuran fasilitas kesehatan yang lebih besar memiliki hubungan berlawanan dengan efisiensi (Gok & Sezen, 2012; Sepehrdust & Rajabi, 2013; Jehu-Appiah et al., 2014; Yang & Zeng, 2014), dan yang lain menemukan yang sebaliknya (Lasso , 1986; Masiye, 2007; Rattanachotphanit et al., 2008). Studi di NBT memiliki hasil yang beragam. Sebuah studi di Yunani tidak menemukan hubungan yang signifikan antara ukuran operasional dan efisiensi (Mitropoulos et al., 2013), sementara sebuah studi di Amerika Serikat serta tinjauannya menemukan bahwa ukuran organisasi yang lebih besar berhubungan berlawanan dengan efisiensi (Worthington, 2004; Shreay et al., 2014). Tinjauan oleh Hadji et al. (2014) menemukan bahwa hubungan antara ukuran dan efisiensi berbentuk U dan bahwa rumah sakit kecil dan besar memiliki efisiensi yang lebih tinggi daripada rumah sakit menengah. Studi lain dalam NBT mengusulkan bahwa efek dari ukuran fasilitas kesehatan berbeda sesuai dengan lokasi dan populasi (Lee et al., 2008a; Asmild et al., 2013). Fasilitas kesehatan yang lebih besar rupanya lebih efisien di daerah perkotaan, sedangkan fasilitas kesehatan yang lebih kecil lebih efisien di daerah pedesaan (Asmild et al., 2013). Sebagian besar analisis efisiensi memasukkan lokasi geografis dari fasilitas kesehatan (misalnya wilayah perkotaan atau pedesaan) sebagai faktor kontekstual. Temuan tinjauan kami berbeda dari penelitian yang dilakukan di NBT seperti Amerika Serikat, yang telah menunjukkan bahwa rumah sakit pedesaan cenderung beroperasi dengan biaya yang lebih rendah karena lebih sedikit komplikasi pasien yang timbul (Ding, 2014). Heimeshoff et al. (2014) juga berpendapat bahwa fasilitas kesehatan di daerah pedesaan di Jerman secara signifikan lebih efisien karena kepadatan dokter yang lebih rendah, yang mengarah pada tingkat hunian yang lebih tinggi. Namun, penjelasan ini hanya boleh diterapkan dalam situasi homogen di mana ada akses fisik yang sama ke fasilitas kesehatan dan kesadaran kesehatan yang sama di antara populasi umum.

Sembilan studi memasukkan kualitas sebagai variabel kontekstual dalam analisis tahap kedua dari efisiensi perawatan kesehatan di NBRM. Indikator yang digunakan sebagai proksi untuk kualitas berkisar dari satu variabel tunggal, seperti akreditasi fasilitas kesehatan, kepuasan pasien, atau tingkat kematian, hingga indeks kualitas gabungan termasuk indikator struktural dan proses. Hasil dalam NBRM menunjukkan hasil yang beragam; beberapa studi tidak menemukan keseimbangan antara kualitas dan efisiensi (Somanathan et al., 2000; Alhassan et al., 2015; Obure et al., 2016), dan yang lain menemukan keseimbangan yang bervariasi dengan ukuran, terutama di kecil dan fasilitas kesehatan menengah (Gok & Sezen, 2013; Yang & Zeng, 2014). Sehubungan dengan NBT, tinjauan oleh Worthington (2004) menemukan bahwa beberapa studi menunjukkan hubungan negatif antara kualitas dan efisiensi. Peneliti berhipotesis bahwa peningkatan kualitas kemungkinan membutuhkan sumber daya tambahan termasuk teknologi medis yang lebih maju dan lebih mahal, sehingga mengurangi efisiensi (Worthington, 2004).

Struktur pasar dalam tinjauan yang sama telah diukur terutama dengan menggunakan indeks persaingan pasar, yang telah semakin banyak digunakan sebagai variabel kontekstual dalam penelitian tentang efisiensi dalam NBT. Namun, ini lebih jarang digunakan dalam NBRM, dan hanya sembilan studi dalam tinjauan ini menggabungkan struktur pasar. Temuan serupa di NBRM dan NBT; hasilnya beragam terkait hubungan antara persaingan pasar dan efisiensi (Worthington, 2004). Beberapa sumber potensial lain dari inefisiensi teknis dalam pelayanan kesehatan, seperti korupsi dan penipuan, tidak pernah dimasukkan dalam pengaturan NBRM atau NBT (Chisholm & Evans, 2010). Tinjauan ini menunjukkan bahwa efisiensi fasilitas kesehatan tidak hanya dipengaruhi oleh faktor internal tetapi juga oleh faktor eksternal yang berada di luar kendali sektor kesehatan. Temuan ini menekankan perlunya dimasukkannya tindakan antar-sektor untuk meningkatkan efisiensi.

### Kerangka Analisis

Input, output dan indikator kontekstual yang dominan diidentifikasi berdasarkan tinjauan literatur dan ketersediaan variabel dalam set data. Kerangka analisis efisiensi yang menunjukkan hubungan antara pilihan input dan output, pengaruh faktor kontekstual dapat dilihat pada Gambar 4.6. Kerangka kerja analitis yang jelas membantu memahami penentu efisiensi dan elemen-elemen ini diterapkan dalam analisis empiris nanti. Indikator input mewakili berbagai jenis sumber daya di fasilitas kesehatan untuk menyediakan berbagai layanan kesehatan. Faktor penentu efisiensi fasilitas kesehatan juga dipengaruhi oleh faktor kontekstual baik faktor internal maupun eksternal. Faktor internal cenderung dikendalikan oleh manajer fasilitas kesehatan, sedangkan faktor eksternal cenderung dikendalikan oleh peraturan kebijakan nasional atau pemangku kepentingan lain di luar sektor kesehatan.

## Keterbatasan

Temuan-temuan dari tinjauan ini bergantung pada beberapa batasan. Studi yang berpotensi relevan dalam bahasa selain bahasa Inggris dieksklusi. Studi ini berfokus pada langkah-langkah efisiensi khusus untuk fasilitas kesehatan dan mengeksklusi studi efisiensi di setting lain. Selain itu, penelitian ini hanya berfokus pada variasi dalam efisiensi menurut kepemilikan, tanpa memperhitungkan cara-cara di mana efisiensi bervariasi dengan skema penggantian yang berbeda di sektor publik dan swasta. Tujuan kami adalah untuk memberikan tinjauan menyeluruh, dan karena itu kualitas studi asli dinilai menggunakan alat validitas yang relatif sederhana daripada protokol kompleks yang digunakan dalam ulasan Cochrane atau Campbell.

## Kesimpulan

Bab ini mengulas studi pengukuran efisiensi yang ada di NBRM saat ini. Tinjauan ini mengidentifikasi metode efisiensi serta faktor kontekstual yang sebagian besar telah digunakan dalam studi efisiensi NBR. Tinjauan ini memberikan tinjauan komprehensif pengukuran efisiensi bagi para peneliti.

Para peneliti yang melakukan penelitian lebih lanjut dapat mempertimbangkan berbagai sumber yang lebih luas, termasuk sumber-sumber tambahan *grey literature*, serta kerja kolaboratif yang memungkinkan para peneliti untuk menangkap literatur dalam berbagai bahasa. Dalam tiga bab berikutnya, kami melanjutkan ke studi empiris, dimulai dengan penilaian kinerja dan faktor-faktor penentu efisiensi di fasilitas pelayanan primer Indonesia dan rumah sakit di Bab 5. Bab 6 berfokus pada kinerja fasilitas pelayanan primer Indonesia, sedangkan Bab 7 menganalisis kinerja rumah sakit Indonesia.
